name: PR Tests

on:
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Lint Python code
      working-directory: ./python
      run: |
        flake8 agentbay tests examples
        black --check agentbay tests examples

  python-tests:
    needs: lint
    uses: ./.github/workflows/python-tests.yml
    secrets: inherit
